### ISSUE TITLE
Fix Wiki  small code example typos

### ISSUE THREAD

**Issue by mar1n3r0** [vardius/gorouter#16]
I am trying out the examples and spotted a few typos which prevent some of them running as described. Please share Wiki access so I can fix them as I run the tests.

I am new to Go and would appreciate some help on the following: 
```
import (
        "github.com/vardius/gorouter/v4/context"
)

main.go:10:9: cannot find package "github.com/vardius/gorouter/v4/context"
```

How does this thing work with version name-spacing ?

**Comment by vardius** [comment]
try `export GO111MODULE=on` and `go get -u -v`
