### ISSUE TITLE
When to prefer gorouter over httprouter

### ISSUE THREAD

**Issue by anilmaurya** [vardius/gorouter#34]
Hi @vardius 

Can you help me understand advantages of gorouter over [httprouter](https://github.com/julienschmidt/httprouter) ?

**Comment by vardius** [comment]
Hi @anilmaurya [gorouter](https://rafallorenz.com/gorouter/) comes with:
- build-in middleware system with order by priority
- parameters with flexible patterns including regexp wildcards
- support for both native net/http or valyala/fasthttp

**Comment by anilmaurya** [comment]
Hi @vardius 

Thank you for the reply

I think you should add it in Readme or highlight it somewhere.

**Comment by vardius** [comment]
@anilmaurya it is highlighted on the website https://rafallorenz.com/gorouter/
![image](https://user-images.githubusercontent.com/6569206/115352392-a8c04180-a1fa-11eb-9e36-1a447614c5f0.png)

**Comment by anilmaurya** [comment]
ohh, I missed it.

Thanks for reply.
