### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by vardius** [vardius/gorouter#8]
Tests could use some refactor, there are multiple case scenario that repeats just for different settings etc.

**Comment by frytyler** [comment]
Hey @vardius I'm interested in working on some golang project and stumbled across this however I feel like a huge noobie right now because I have no idea how to get this up and running. 

I can't seem to get the dependencies installed for the project. 

Any tips? 

I can update the contributing guide as well for 1st time contributors to help for next time. 

If I can get setup I'll work to get some of the tests refactored.

**Comment by vardius** [comment]
Hi @frytyler nice to hear that you'd like to help

this router does not have any external dependencies therefore you do not have to install anything using dep or vgo. Simply fork this repository, make changes and create a pull request.

**Comment by frytyler** [comment]
Thanks for the quick response. When I run that I get: 

`cannot find package "github.com/julienschmidt/httprouter"` 

but honestly I'm a JS dev first time really trying out `go` I could be doing something completely wrong haha

```bash

# in my $GOPATH I ran
go get github.com/frytyler/gorouter

cd $GOPATH/src/github.com/frytyler/gorouter

go test -v -race

```

```
# github.com/vardius/gorouter
benchmark_test.go:8:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
        /usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)
        /Users/tylerfry/sites/go/src/github.com/julienschmidt/httprouter (from $GOPATH)
FAIL    github.com/vardius/gorouter [setup failed]
```

**Comment by vardius** [comment]
Ohhh sorry i completely forgot about that, this is a benchmark i did to compere with other router out there.

You can simple comment out `benchmark_test.go` file. 
Or just do `go get github.com/julienschmidt/httprouter` from CLI console

**Comment by frytyler** [comment]
Great `dep` worked seamlessly so I'll add that in a PR regardless if I make any improvements to the tests.

**Comment by vardius** [comment]
Closing due to long inactivity
